### ISSUE TITLE
Definição de data para meetup do GOPHP

### ISSUE THREAD

**Issue by brenodouglas** [GOPHP/meetup#1]
Como conversado pelo telegram a comunidade estará se reunindo para realização de meetups mensais e este sendo o primeiro gostaria de definir data para o mesmo. Deixo como sugestão para votação nesta issue as seguintes datas e horas:

11/05/2018 20:00 
ou
12/05/2018 09:00

Caso tenha sugestão pode deixar no comentário que estamos aberto. Gostaria de finalizar essa escolha até o dia 21/04/2018 (próximo sabado) para que possamos seguir com a submissão de palestras que deixo como sugestão de 20 minutos (e também aberto a sugestões).

**Comment by r-guimaraes** [comment]
12/05/2018 09:00

**Comment by fernandopedro** [comment]
12/05/2018 09:00

**Comment by tifannyknox** [comment]
Dia 12! Noix

**Comment by Simplesmente** [comment]
12/05/2018 09:00

**Comment by wlandim** [comment]
12/05/2018 09:00

**Comment by claudionts** [comment]
12/05/2018 09:00

**Comment by hakuno** [comment]
12/05/2018 09:00

**Comment by NikolasMatias** [comment]
12/05/2018 09:00

**Comment by brenodouglas** [comment]
o dia escolhido foi: 12/05/2018 as 9:00 A.M. 

A issue para submissão foi aberta e esta será fechada.

https://github.com/GOPHP/meetup/issues/2
